/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CCIPTokenAndDataReceiver } from "./CCIPTokenAndDataReceiver";
export type { MyNFT } from "./MyNFT";
